apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: techieglobusdep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: depv1
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 80
            preference:
              matchExpressions:
              - key: capacity
                operator: In
                values:
                - low
          - weight: 20
            preference:
              matchExpressions:
              - key: resource
                operator: In
                values:
                - high
      containers:
      - image: samridhrakesh/appv1:v1
        name: nodejs

