apiVersion: v1
kind: Service
metadata:
  name: apacheservice
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 443

  selector:
    env: nginx
  
  
