apiVersion: apps/v1beta1
kind: Deployments
metadata:
  name: mysoft-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      env: promethius
      
  template:
    metadata:
      labels:
        env: promethius
    spec:
      containers:
      - arg:
        - --storage.tsdb.retention.time=5h
        - --config.file=/etc/prometheus/prometheus.yml
      - image: prom/prometheus
        name: promethius
        ports:
        - containerPort: 9090
     
---
apiVersion: v1
kind: Service
metadata:
  name: promethius-service
spec:
  type: NodePort
  selector:
    env: promethius
  ports:
  - port: 9090
    targetPort: 9090
